# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Persistr Hugo Theme"
license = "MIT"
licenselink = "https://github.com/SDA/persistr-daily-tips/blob/master/LICENSE.md"
description = "Theme for Persistr Daily Tips Hugo Site"
homepage = "https://github.com/SDA/persistr-daily-tips"
tags = ["Persistr"]
features = ["posts", "shortcodes", "related content", "comments"]
min_version = 0.30.2

[author]
  name = "Sasha Jolich"
  homepage = "https://github.com/sasadjolic"
